"""Build the small manifest-derived human metrics summary."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from agentic_simulation_lab.core.reporting import metrics


def render(root: Path = ROOT) -> str:
    data = metrics(root)
    rows = [
        ("Physics domains", data["domains"]),
        ("Catalog entries", data["cases"]),
        *((status, count) for status, count in data["statuses"].items()),
        *((f"{role.title()}-role entries", count) for role, count in data["roles"].items()),
    ]
    table = "\n".join(f"| {label} | {count} |" for label, count in rows)
    solvers = "\n".join(f"| {label} | {count} |" for label, count in data["solver_coverage"].items())
    return f"""# Project metrics

<!-- Generated by tools/build_project_metrics.py from benchmarks/*/manifest.json. Do not edit manually. -->

The domain manifests are authoritative for current catalog counts and labels. Rebuild this file with
`python tools/build_project_metrics.py`; verify it with `python tools/build_project_metrics.py --check`.

| Metric | Count |
|---|---:|
{table}

| Solver label | Entries |
|---|---:|
{solvers}

Historical run counts and integration versions belong in dated evidence files, not in this generated current-state summary.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    target = ROOT / "docs" / "PROJECT_METRICS.md"
    rendered = render()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != rendered:
            print("PROJECT_METRICS.md is stale", file=sys.stderr)
            return 1
        return 0
    target.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
