"""Build the human benchmark gallery and deterministic documentation SVGs.

The gallery reads only repository-owned manifests, case source, and compact
reference evidence.  Its SVGs are explanatory evidence graphics, never solver
screenshots or fabricated field contours.
"""

from __future__ import annotations

import argparse
import ast
import html
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "benchmarks" / "catalog.json"
ASSETS = ROOT / "docs" / "assets"
MARKER = "<!-- Generated by tools/build_gallery.py from repository-owned data. -->"

DOMAIN_ZH = {
    "acoustics": "声学",
    "cfd": "计算流体力学",
    "dem": "离散元",
    "electromagnetics": "电磁场",
    "materials": "材料本构",
    "mechanics": "结构与动力学",
    "multiphysics": "多物理场耦合",
    "phase_reactive": "相变与反应流",
    "porous_geomechanics": "多孔介质与岩土",
    "sph": "SPH 自由液面",
    "thermal": "热分析",
}

DOMAIN_EN = {
    "acoustics": "Acoustics",
    "cfd": "Computational fluid dynamics",
    "dem": "Discrete element method",
    "electromagnetics": "Electromagnetics",
    "materials": "Material models",
    "mechanics": "Mechanics and dynamics",
    "multiphysics": "Multiphysics coupling",
    "phase_reactive": "Phase change and reactive flow",
    "porous_geomechanics": "Porous media and geomechanics",
    "sph": "SPH free-surface flow",
    "thermal": "Thermal analysis",
}

SHOWCASE = {
    ("mechanics", "static-cantilever"): "showcase/static-cantilever.svg",
    ("cfd", "fluent-laminar-channel"): "showcase/laminar-channel.svg",
    ("multiphysics", "cht-fluent"): "showcase/conjugate-heat-transfer.svg",
    ("acoustics", "acoustic-tube"): "showcase/acoustic-tube.svg",
    ("dem", "particle-freefall"): "showcase/particle-freefall.svg",
    ("sph", "sph-dam-break"): "showcase/sph-dam-break.svg",
}

RESULT_VISUALS = {
    "mechanics": "static-cantilever",
    "thermal": "thermal-conduction",
    "cfd": "fluent-cylinder-unsteady",
    "multiphysics": "cht-fluent",
    "materials": "plasticity",
    "electromagnetics": "magnetostatic",
    "acoustics": "acoustic-cavity-modal",
    "porous_geomechanics": "terzaghi-consolidation",
    "dem": "angle-of-repose",
    "sph": "sph-dam-break",
    "phase_reactive": "fluent-melting",
}

CURATED_VALIDATION = {
    ("mechanics", "static-cantilever"): "Euler–Bernoulli tip deflection; 0.100143 mm vs 0.100000 mm (0.143% error)",
    ("cfd", "fluent-laminar-channel"): "Poiseuille profile, pressure drop, and mass conservation; profile L2 error 0.210%",
    ("multiphysics", "cht-fluent"): "Global energy closure and temperature bounds; historical imbalance 0.900%",
    ("acoustics", "acoustic-tube"): "Quarter-wave resonance; 86.0 Hz vs 85.81 Hz (0.221% error)",
    ("dem", "particle-freefall"): "Constant-gravity kinematics; maximum position error 1.34 µm",
    ("sph", "sph-dam-break"): "Front advance, mass conservation, finite history, and projection checks",
    ("electromagnetics", "electrostatic"): "Historical regression remains FAIL; current supported-path diagnosis is separately BLOCKED",
    ("multiphysics", "fsi-turek-hron"): "Formal comparison window was not reached; historical status remains FAIL",
    ("phase_reactive", "premixed-combustion"): "Required combustion checks failed; targeted diagnostic evidence is preserved",
    ("phase_reactive", "reactive-cht"): "10-step energy error 15.842% exceeds the unchanged 10% limit",
}


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def load_catalog() -> dict[str, object]:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def case_source(case: dict[str, object]) -> str:
    path = ROOT / str(case["entrypoint"])
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return str(case.get("analysis") or case["title"])
    doc = ast.get_docstring(tree) or str(case.get("analysis") or case["title"])
    first = doc.splitlines()[0].strip()
    if ":" in first and first.lower().startswith(("case ", "phase ")):
        first = first.split(":", 1)[1].strip()
    return first.rstrip(".")


def declared_checks(case: dict[str, object]) -> list[str]:
    path = ROOT / str(case["entrypoint"])
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if not any(isinstance(target, ast.Name) and target.id == "checks" for target in targets):
            continue
        value = node.value
        if isinstance(value, ast.Dict):
            keys = [key.value for key in value.keys if isinstance(key, ast.Constant) and isinstance(key.value, str)]
            return keys[:3]
    return []


def validation_text(domain: str, case: dict[str, object]) -> str:
    key = (domain, str(case["slug"]))
    if key in CURATED_VALIDATION:
        return CURATED_VALIDATION[key]
    checks = declared_checks(case)
    if checks:
        return "; ".join(item.replace("_", " ") for item in checks)
    if case.get("evidence"):
        return "Compact historical evidence is linked; no case-specific metric is duplicated here"
    return "No attributable run evidence; status remains NOT_RUN"


def svg_document(title: str, desc: str, body: str, *, height: int = 420, background: str = "#081018") -> str:
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="{height}" viewBox="0 0 1200 {height}" role="img" aria-labelledby="title desc">
{MARKER}
<title id="title">{esc(title)}</title>
<desc id="desc">{esc(desc)}</desc>
<rect width="1200" height="{height}" rx="28" fill="{background}"/>
{body}
</svg>
'''


def write_output(path: Path, content: str, check: bool, errors: list[str]) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            errors.append(f"{path.relative_to(ROOT).as_posix()} is stale")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def hero_svg(case_count: int, domain_count: int, counts: Counter[str]) -> str:
    body = f'''
<g font-family="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif">
  <text x="64" y="62" fill="#67e8f9" font-size="20" font-weight="700" letter-spacing="3">AGENT-FIRST ENGINEERING SIMULATION</text>
  <text x="64" y="132" fill="#f8fafc" font-size="58" font-weight="750">Agentic Simulation Lab</text>
  <text x="64" y="178" fill="#cbd5e1" font-size="25">Reproducible Ansys workflows judged by physics—not exit codes.</text>
  <g transform="translate(64 232)" font-family="ui-monospace,SFMono-Regular,Consolas,monospace" font-size="18">
    <rect width="150" height="58" rx="10" fill="#102331" stroke="#2b5164"/><text x="75" y="36" text-anchor="middle" fill="#f8fafc">physical intent</text>
    <path d="M150 29H182" stroke="#67e8f9" stroke-width="3"/><path d="M176 22l10 7-10 7" fill="none" stroke="#67e8f9" stroke-width="3"/>
    <rect x="188" width="120" height="58" rx="10" fill="#102331" stroke="#2b5164"/><text x="248" y="36" text-anchor="middle" fill="#f8fafc">Agent</text>
    <path d="M308 29H340" stroke="#67e8f9" stroke-width="3"/><path d="M334 22l10 7-10 7" fill="none" stroke="#67e8f9" stroke-width="3"/>
    <rect x="346" width="142" height="58" rx="10" fill="#102331" stroke="#2b5164"/><text x="417" y="36" text-anchor="middle" fill="#f8fafc">script / CLI</text>
    <path d="M488 29H520" stroke="#67e8f9" stroke-width="3"/><path d="M514 22l10 7-10 7" fill="none" stroke="#67e8f9" stroke-width="3"/>
    <rect x="526" width="130" height="58" rx="10" fill="#102331" stroke="#2b5164"/><text x="591" y="36" text-anchor="middle" fill="#f8fafc">solver</text>
    <path d="M656 29H688" stroke="#67e8f9" stroke-width="3"/><path d="M682 22l10 7-10 7" fill="none" stroke="#67e8f9" stroke-width="3"/>
    <rect x="694" width="166" height="58" rx="10" fill="#123027" stroke="#2d6a55"/><text x="777" y="36" text-anchor="middle" fill="#a7f3d0">physics checks</text>
  </g>
  <g transform="translate(64 340)">
    <text fill="#f8fafc" font-size="38" font-weight="700">{case_count}</text><text x="78" y="0" fill="#94a3b8" font-size="18">cases</text>
    <text x="190" fill="#f8fafc" font-size="38" font-weight="700">{domain_count}</text><text x="242" y="0" fill="#94a3b8" font-size="18">physics domains</text>
    <text x="430" fill="#86efac" font-size="22" font-weight="700">{counts['PASS']} PASS</text>
    <text x="550" fill="#fda4af" font-size="22" font-weight="700">{counts['FAIL']} FAIL</text>
    <text x="650" fill="#fcd34d" font-size="22" font-weight="700">{counts['BLOCKED']} BLOCKED</text>
    <text x="820" fill="#cbd5e1" font-size="22" font-weight="700">{counts['NOT_RUN']} NOT_RUN</text>
  </g>
</g>'''
    return svg_document(
        "Agentic Simulation Lab",
        f"Agent-first reproducible simulation workflow with {case_count} cases across {domain_count} domains and honest evidence statuses.",
        body,
    )


def workflow_svg() -> str:
    labels = [("Human intent", "scope + physics"), ("Coding Agent", "inspect + orchestrate"), ("Script / CLI", "reproducible setup"), ("Ansys solver", "numerical simulation"), ("Validation", "analytical + physical"), ("Result", "PASS / FAIL / BLOCKED")]
    cards = []
    for index, (title, subtitle) in enumerate(labels):
        x = 40 + index * 190
        cards.append(f'<rect x="{x}" y="94" width="160" height="112" rx="14" fill="#ffffff" stroke="#9fb6c5"/>')
        cards.append(f'<text x="{x + 80}" y="138" text-anchor="middle" fill="#102331" font-size="21" font-weight="700">{esc(title)}</text>')
        cards.append(f'<text x="{x + 80}" y="172" text-anchor="middle" fill="#526879" font-size="17">{esc(subtitle)}</text>')
        if index < len(labels) - 1:
            cards.append(f'<path d="M{x + 160} 150H{x + 184}" stroke="#087e8b" stroke-width="4"/><path d="M{x + 177} 142l11 8-11 8" fill="none" stroke="#087e8b" stroke-width="4"/>')
    body = f'''<g font-family="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif">
<text x="40" y="48" fill="#102331" font-size="28" font-weight="750">One auditable chain from intent to evidence</text>
{''.join(cards)}
<text x="40" y="254" fill="#526879" font-size="18">The Agent coordinates the workflow. The solver computes the solution. Declared physics checks determine the status.</text>
</g>'''
    return svg_document("Agent-first simulation workflow", "Six-stage workflow from human physical intent to a structured, physics-validated result.", body, height=290, background="#eef4f7")


def showcase_board_svg() -> str:
    cards = [
        ("Mechanics", "Static cantilever", "0.143% tip-error", "#67e8f9", "M24 120 C105 120 170 132 244 168"),
        ("CFD", "Laminar channel", "0.210% profile L2", "#67e8f9", "M24 90 C230 112 230 158 24 180"),
        ("Multiphysics", "Conjugate heat transfer", "0.900% imbalance", "#f59e0b", "M40 135 H232"),
        ("Acoustics", "Standing-wave tube", "0.221% frequency error", "#67e8f9", "M24 142 C70 75 115 75 160 142 S240 210 262 142"),
        ("DEM", "Particle free fall", "1.34 µm max error", "#f59e0b", "M145 76 V188"),
        ("SPH", "Dam break", "front + mass checks", "#67e8f9", "M28 175 H260"),
    ]
    content = []
    for index, (domain, title, metric, color, path) in enumerate(cards):
        col, row = index % 3, index // 3
        x, y = 44 + col * 374, 102 + row * 278
        content.append(f'<g transform="translate({x} {y})"><rect width="344" height="242" rx="18" fill="#0d1b25" stroke="#294555"/>')
        content.append(f'<text x="24" y="38" fill="{color}" font-size="16" font-weight="700" letter-spacing="2">{domain.upper()}</text>')
        content.append(f'<text x="24" y="76" fill="#f8fafc" font-size="25" font-weight="700">{esc(title)}</text>')
        content.append(f'<path d="{path}" fill="none" stroke="{color}" stroke-width="6"/>')
        if domain == "DEM":
            content.append('<circle cx="145" cy="90" r="12" fill="#67e8f9"/><circle cx="145" cy="142" r="12" fill="#48b7c8"/><circle cx="145" cy="188" r="12" fill="#2d8fa0"/>')
        if domain == "SPH":
            content.append(''.join(f'<circle cx="{36 + (i % 8) * 22}" cy="{168 - (i // 8) * 20}" r="7" fill="#67e8f9"/>' for i in range(24)))
        if domain == "Multiphysics":
            content.append('<rect x="40" y="102" width="92" height="68" rx="8" fill="#16415a"/><rect x="140" y="102" width="92" height="68" rx="8" fill="#63381f"/><path d="M118 136h42" stroke="#f8fafc" stroke-width="4"/>')
        content.append(f'<text x="24" y="220" fill="#86efac" font-size="19" font-weight="700">{esc(metric)}</text></g>')
    body = f'''<g font-family="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif">
<text x="44" y="50" fill="#f8fafc" font-size="34" font-weight="750">Six physics stories, one evidence contract</text>
<text x="44" y="80" fill="#94a3b8" font-size="18">Historical values from compact repository evidence; schematics are explanatory, not solver contours.</text>
{''.join(content)}
</g>'''
    return svg_document("Simulation evidence showcase", "Six representative validated simulations across mechanics, CFD, multiphysics, acoustics, DEM, and SPH.", body, height=670)


def showcase_svgs() -> dict[str, str]:
    font = "font-family=\"-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif\""
    common_label = '<text x="52" y="44" fill="#67e8f9" font-size="17" font-weight="700" letter-spacing="2">HISTORICAL EVIDENCE VISUALIZATION</text>'
    return {
        "showcase/static-cantilever.svg": svg_document("Static cantilever benchmark", "A beam deflection schematic and historical comparison with Euler-Bernoulli theory.", f'''<g {font}>{common_label}<text x="52" y="88" fill="#f8fafc" font-size="34" font-weight="750">Static cantilever</text><text x="52" y="122" fill="#94a3b8" font-size="19">Mechanical / MAPDL · PASS</text><path d="M430 145 C620 148 780 176 980 260" fill="none" stroke="#67e8f9" stroke-width="16"/><rect x="400" y="112" width="28" height="180" fill="#64748b"/><path d="M980 220v72m-15-18 15 18 15-18" stroke="#f59e0b" stroke-width="5" fill="none"/><text x="52" y="240" fill="#f8fafc" font-size="28">0.100143 mm</text><text x="52" y="272" fill="#94a3b8" font-size="18">solver tip displacement</text><text x="52" y="330" fill="#86efac" font-size="26" font-weight="700">0.143% error</text><text x="52" y="360" fill="#94a3b8" font-size="18">vs 0.100000 mm beam theory</text></g>'''),
        "showcase/laminar-channel.svg": svg_document("Laminar channel benchmark", "A parabolic Poiseuille velocity profile with historical validation errors.", f'''<g {font}>{common_label}<text x="52" y="88" fill="#f8fafc" font-size="34" font-weight="750">Laminar channel flow</text><text x="52" y="122" fill="#94a3b8" font-size="19">Fluent · PASS</text><path d="M475 90v260M475 90h420M475 350h420" stroke="#64748b" stroke-width="3"/><path d="M475 90 C900 150 900 290 475 350" fill="none" stroke="#67e8f9" stroke-width="8"/><path d="M475 220h390" stroke="#f59e0b" stroke-width="3" stroke-dasharray="10 10"/><text x="52" y="234" fill="#f8fafc" font-size="28">Poiseuille profile</text><text x="52" y="278" fill="#86efac" font-size="26" font-weight="700">0.210% L2 error</text><text x="52" y="316" fill="#cbd5e1" font-size="20">pressure-drop error 0.150%</text><text x="52" y="348" fill="#cbd5e1" font-size="20">mass-flow checks declared</text></g>'''),
        "showcase/conjugate-heat-transfer.svg": svg_document("Conjugate heat transfer benchmark", "Fluid and solid regions exchange heat while a global energy balance is checked.", f'''<g {font}>{common_label}<text x="52" y="88" fill="#f8fafc" font-size="34" font-weight="750">Conjugate heat transfer</text><text x="52" y="122" fill="#94a3b8" font-size="19">Fluent · PASS</text><rect x="500" y="98" width="270" height="240" rx="16" fill="#123b55" stroke="#67e8f9"/><rect x="770" y="98" width="270" height="240" rx="16" fill="#5a3420" stroke="#f59e0b"/><text x="635" y="220" text-anchor="middle" fill="#bae6fd" font-size="30">fluid</text><text x="905" y="220" text-anchor="middle" fill="#fed7aa" font-size="30">solid</text><path d="M700 170h140m-20-16 24 16-24 16" stroke="#f8fafc" stroke-width="6" fill="none"/><text x="52" y="244" fill="#f8fafc" font-size="25">global energy closure</text><text x="52" y="292" fill="#86efac" font-size="34" font-weight="750">0.900% imbalance</text><text x="52" y="334" fill="#cbd5e1" font-size="19">temperature bounds also checked</text></g>'''),
        "showcase/acoustic-tube.svg": svg_document("Acoustic tube benchmark", "A standing-wave tube schematic and historical quarter-wave resonance comparison.", f'''<g {font}>{common_label}<text x="52" y="88" fill="#f8fafc" font-size="34" font-weight="750">Acoustic tube</text><text x="52" y="122" fill="#94a3b8" font-size="19">MAPDL / Mechanical · PASS</text><rect x="450" y="126" width="620" height="180" fill="#0e1c27" stroke="#64748b" stroke-width="4"/><path d="M470 216 C540 115 610 115 680 216 S820 317 890 216 S1010 115 1050 216" fill="none" stroke="#67e8f9" stroke-width="7"/><line x1="450" y1="126" x2="450" y2="306" stroke="#f8fafc" stroke-width="12"/><text x="52" y="238" fill="#f8fafc" font-size="28">86.0 Hz measured</text><text x="52" y="282" fill="#cbd5e1" font-size="22">85.81 Hz quarter-wave theory</text><text x="52" y="330" fill="#86efac" font-size="30" font-weight="750">0.221% error</text></g>'''),
        "showcase/particle-freefall.svg": svg_document("Particle free-fall benchmark", "A particle trajectory schematic compared with constant-gravity kinematics.", f'''<g {font}>{common_label}<text x="52" y="88" fill="#f8fafc" font-size="34" font-weight="750">Particle free fall</text><text x="52" y="122" fill="#94a3b8" font-size="19">Rocky · PASS</text><path d="M690 88v278" stroke="#64748b" stroke-width="3" stroke-dasharray="8 10"/><circle cx="690" cy="118" r="19" fill="#67e8f9"/><circle cx="690" cy="190" r="19" fill="#4bc4d4"/><circle cx="690" cy="310" r="19" fill="#2d8fa0"/><path d="M735 105v210m-14-18 14 18 14-18" stroke="#f59e0b" stroke-width="5" fill="none"/><text x="52" y="238" fill="#f8fafc" font-size="27">z(t) against constant gravity</text><text x="52" y="290" fill="#86efac" font-size="32" font-weight="750">1.34 µm max error</text><text x="52" y="334" fill="#cbd5e1" font-size="20">velocity error below 1×10⁻¹² m/s</text></g>'''),
        "showcase/sph-dam-break.svg": svg_document("SPH dam-break benchmark", "A geometry and validation schematic for the narrow 3-D SPH dam-break case; it is not a solver contour.", f'''<g {font}><text x="52" y="44" fill="#67e8f9" font-size="17" font-weight="700" letter-spacing="2">GEOMETRY + VALIDATION SCHEMATIC · NOT A CONTOUR</text><text x="52" y="88" fill="#f8fafc" font-size="34" font-weight="750">SPH dam break</text><text x="52" y="122" fill="#94a3b8" font-size="19">Rocky · PASS</text><path d="M480 102v240h610" fill="none" stroke="#94a3b8" stroke-width="5"/><g fill="#67e8f9">{''.join(f'<circle cx="{510 + (i % 7) * 22}" cy="{315 - (i // 7) * 22}" r="8"/>' for i in range(28))}</g><g fill="#2d8fa0">{''.join(f'<circle cx="{690 + i * 24}" cy="{320 - (i % 3) * 13}" r="7"/>' for i in range(14))}</g><path d="M650 220h190m-20-15 24 15-24 15" stroke="#f59e0b" stroke-width="5" fill="none"/><text x="52" y="230" fill="#f8fafc" font-size="25">front advance + mass conservation</text><text x="52" y="276" fill="#86efac" font-size="30" font-weight="750">historical PASS</text><text x="52" y="320" fill="#cbd5e1" font-size="19">finite history · ≥5 snapshots</text><text x="52" y="352" fill="#cbd5e1" font-size="19">Eulerian projection checked separately</text></g>'''),
    }


def domain_svg(domain: dict[str, object]) -> str:
    cases = list(domain["cases"])
    counts = Counter(str(case["status"]) for case in cases)
    colors = {"PASS": "#22c55e", "FAIL": "#fb7185", "BLOCKED": "#fbbf24", "NOT_RUN": "#94a3b8", "PARTIAL": "#60a5fa"}
    total = max(len(cases), 1)
    x = 52.0
    bars = []
    for status in ("PASS", "FAIL", "BLOCKED", "NOT_RUN", "PARTIAL"):
        width = 1096 * counts[status] / total
        if width:
            bars.append(f'<rect x="{x:.2f}" y="176" width="{width:.2f}" height="28" fill="{colors[status]}"/>')
            x += width
    examples = " · ".join(str(case["slug"]) for case in cases[:4])
    body = f'''<g font-family="-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif">
<text x="52" y="48" fill="#67e8f9" font-size="17" font-weight="700" letter-spacing="2">DOMAIN EVIDENCE MAP · NOT A CASE CONTOUR</text>
<text x="52" y="96" fill="#f8fafc" font-size="38" font-weight="750">{esc(DOMAIN_EN.get(str(domain['domain']), domain['title']))}</text>
<text x="52" y="132" fill="#94a3b8" font-size="20">{len(cases)} catalog entries · statuses from manifest evidence</text>
{''.join(bars)}
<text x="52" y="252" fill="#86efac" font-size="20" font-weight="700">{counts['PASS']} PASS</text>
<text x="180" y="252" fill="#fda4af" font-size="20" font-weight="700">{counts['FAIL']} FAIL</text>
<text x="286" y="252" fill="#fcd34d" font-size="20" font-weight="700">{counts['BLOCKED']} BLOCKED</text>
<text x="460" y="252" fill="#cbd5e1" font-size="20" font-weight="700">{counts['NOT_RUN']} NOT_RUN</text>
<text x="52" y="306" fill="#cbd5e1" font-size="18">{esc(examples)}</text>
<text x="52" y="350" fill="#64748b" font-size="17">Use the table below for case-specific physics, code, validation evidence, and exact status.</text>
</g>'''
    return svg_document(f"{domain['title']} evidence map", f"Status distribution and example cases for the {domain['title']} domain. This is a portfolio map, not a simulation contour.", body, height=390)


def gallery_markdown(catalog: dict[str, object], *, chinese: bool) -> str:
    domains = list(catalog["domains"])
    cases = [case for domain in domains for case in domain["cases"]]
    counts = Counter(str(case["status"]) for case in cases)
    if chinese:
        intro = f'''# 仿真案例总览

[English](BENCHMARKS.md) | **简体中文**

<!-- 由 tools/build_gallery.py 根据 manifest、案例源码与 reference evidence 生成，请勿手工编辑表格。 -->

这里列出公开目录中的全部 **{len(cases)}** 个案例，覆盖 **{len(domains)}** 个物理领域。状态直接来自 manifest：`PASS` {counts['PASS']} 个、`FAIL` {counts['FAIL']} 个、`BLOCKED` {counts['BLOCKED']} 个、`NOT_RUN` {counts['NOT_RUN']} 个。它们是历史证据，不代表当前机器必然得到相同结果。

每个领域先保留一张 SVG 领域图，用于展示案例构成与状态分布，**不是仿真云图**；随后给出一张由精简求解器数据确定性重建的 PNG 结果图。没有真实结果图的案例不会用装饰性占位图冒充结果。完整来源清单见[真实仿真结果与来源](SIMULATION_RESULTS.zh-CN.md)。案例名称与源码 docstring 保留英文，避免生成式翻译造成物理含义漂移。

状态含义见[验证规范](VALIDATION.md)，运行前请先阅读[快速开始](tutorials/quickstart.zh-CN.md)并执行 `info`、`doctor` 和 `--dry-run`。
'''
    else:
        intro = f'''# Simulation and benchmark catalog

**English** | [简体中文](BENCHMARKS.zh-CN.md)

<!-- Generated by tools/build_gallery.py from manifests, case source, and compact reference evidence. Do not edit generated tables manually. -->

This is the complete human-facing index of all **{len(cases)}** public catalog entries across **{len(domains)}** physics domains. Manifest-declared historical status counts are `PASS` {counts['PASS']}, `FAIL` {counts['FAIL']}, `BLOCKED` {counts['BLOCKED']}, and `NOT_RUN` {counts['NOT_RUN']}. They do not guarantee the same outcome on another installation, version, license, mesh, or machine.

Each domain keeps an SVG portfolio/status overview that is **not a simulation contour**, followed by one deterministic PNG reconstructed from compact solver output. Cases without true result figures are not padded with decorative visual placeholders. See [real simulation results and provenance](SIMULATION_RESULTS.md) for the complete source inventory.

Read the [status and validation policy](VALIDATION.md) and the [Quick Start](tutorials/quickstart.md). Always inspect with `info`, diagnose with `doctor`, and use `--dry-run` before an authorized solver execution.
'''
    chunks = [intro]
    for domain in domains:
        domain_slug = str(domain["domain"])
        title = DOMAIN_ZH.get(domain_slug, str(domain["title"])) if chinese else DOMAIN_EN.get(domain_slug, str(domain["title"]))
        chunks.append(f"\n## {title}\n")
        chunks.append(f"\n![{title} evidence map](assets/gallery/{domain_slug}.svg)\n")
        result_slug = RESULT_VISUALS[domain_slug]
        result_case = next(case for case in domain["cases"] if str(case["slug"]) == result_slug)
        result_path = f"assets/simulations/{domain_slug}/{result_slug}.png"
        result_evidence = f"assets/simulations/{domain_slug}/{result_slug}.evidence.json"
        if chinese:
            chunks.append(f"\n![{title}真实求解结果：{result_slug}]({result_path})\n")
            chunks.append(
                f"\n代表结果：[`{domain_slug}/{result_slug}`](../{result_case['entrypoint']}) · "
                f"[精简数值证据]({result_evidence}) · [来源说明](SIMULATION_RESULTS.zh-CN.md)\n"
            )
        else:
            chunks.append(f"\n![{title} solver-derived result: {result_slug}]({result_path})\n")
            chunks.append(
                f"\nRepresentative result: [`{domain_slug}/{result_slug}`](../{result_case['entrypoint']}) · "
                f"[sanitized numeric evidence]({result_evidence}) · [provenance notes](SIMULATION_RESULTS.md)\n"
            )
        if chinese:
            chunks.append("\n| 案例与物理问题 | 求解器 / 类型 | 状态 | 验证依据 / 代表性结果 | 代码、证据与图示 |\n|---|---|---|---|---|\n")
        else:
            chunks.append("\n| Case and physical problem | Solver / role | Status | Validation basis / representative result | Code, evidence, and visual |\n|---|---|---|---|---|\n")
        for case in domain["cases"]:
            slug = str(case["slug"])
            case_link = f"../{case['entrypoint']}"
            problem = case_source(case).replace("|", "\\|")
            solver = str(case.get("solver") or "Not declared").replace("|", "\\|")
            role = str(case.get("role") or "benchmark")
            status = str(case["status"])
            validation = validation_text(domain_slug, case).replace("|", "\\|")
            evidence = case.get("evidence")
            links = [f"[code]({case_link})"]
            if evidence:
                links.append(f"[evidence](../{evidence})")
            if slug == result_slug:
                label = "求解结果 PNG" if chinese else "solver-result PNG"
                links.append(f"[{label}]({result_path})")
            elif (domain_slug, slug) in SHOWCASE:
                label = "解释示意图" if chinese else "explanatory schematic"
                links.append(f"[{label}](assets/{SHOWCASE[(domain_slug, slug)]})")
            chunks.append(f"| [`{domain_slug}/{slug}`]({case_link}) — {problem} | {solver}<br>{role} | **{status}** | {validation} | {' · '.join(links)} |\n")
    chunks.append("\n---\n\n")
    if chinese:
        chunks.append("更新命令：`python tools/build_gallery.py`；一致性检查：`python tools/build_gallery.py --check`。manifest 与 reference evidence 始终是状态事实来源。\n")
    else:
        chunks.append("Update with `python tools/build_gallery.py`; verify freshness with `python tools/build_gallery.py --check`. Manifests and compact reference evidence remain the status sources of truth.\n")
    return "".join(chunks)


def build(check: bool) -> list[str]:
    catalog = load_catalog()
    domains = list(catalog["domains"])
    cases = [case for domain in domains for case in domain["cases"]]
    counts = Counter(str(case["status"]) for case in cases)
    outputs = {
        ASSETS / "hero.svg": hero_svg(len(cases), len(domains), counts),
        ASSETS / "showcase-board.svg": showcase_board_svg(),
        ASSETS / "workflow.svg": workflow_svg(),
        ROOT / "docs" / "BENCHMARKS.md": gallery_markdown(catalog, chinese=False),
        ROOT / "docs" / "BENCHMARKS.zh-CN.md": gallery_markdown(catalog, chinese=True),
    }
    for relative, rendered in showcase_svgs().items():
        outputs[ASSETS / relative] = rendered
    for domain in domains:
        outputs[ASSETS / "gallery" / f"{domain['domain']}.svg"] = domain_svg(domain)
    errors: list[str] = []
    for path, content in outputs.items():
        write_output(path, content, check, errors)
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated gallery content is stale")
    args = parser.parse_args()
    errors = build(args.check)
    for error in errors:
        print(error)
    return bool(errors)


if __name__ == "__main__":
    raise SystemExit(main())
