"""Import compact solver evidence and render deterministic simulation visuals.

Normal builds read only tracked, sanitized JSON evidence.  ``--import-local`` is
the explicit maintainer workflow for importing qualified ignored solver output;
it never copies solver databases, projects, screenshots, or runtime logs.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import html
import json
import math
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = ROOT / "docs" / "assets" / "simulations"
MARKER = "Generated by tools/build_simulation_visuals.py from repository-owned solver-derived evidence."
PNG_RENDER_VERSION = 3
PNG_DPI = 180
PNG_SIZE = (1620, 972)
PALETTE = ("#30123b", "#4145ab", "#2f8ac4", "#26b6a5", "#65cb5e", "#d4d849", "#f6a72c", "#e95b1a", "#b31b2c")
DOMAINS = (
    "mechanics",
    "thermal",
    "cfd",
    "multiphysics",
    "materials",
    "electromagnetics",
    "acoustics",
    "porous_geomechanics",
    "dem",
    "sph",
    "phase_reactive",
)
SLUGS = {
    "mechanics": "static-cantilever",
    "thermal": "thermal-conduction",
    "cfd": "fluent-cylinder-unsteady",
    "multiphysics": "cht-fluent",
    "materials": "plasticity",
    "electromagnetics": "magnetostatic",
    "acoustics": "acoustic-cavity-modal",
    "porous_geomechanics": "terzaghi-consolidation",
    "dem": "angle-of-repose",
    "sph": "sph-dam-break",
    "phase_reactive": "fluent-melting",
}


def rel(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sources(*paths: Path) -> list[dict[str, str]]:
    return [{"path": rel(path), "sha256": sha256(path)} for path in paths]


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def require_pass(path: Path) -> dict[str, Any]:
    payload = read_json(path)
    if payload.get("status") != "PASS":
        raise ValueError(f"source result is not PASS: {rel(path)}")
    return payload


def base_evidence(
    domain: str,
    *,
    solver: str,
    representation: str,
    reference: str,
    source_files: Iterable[Path],
    rerun: bool,
) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "domain": domain,
        "case": SLUGS[domain],
        "status": "PASS",
        "solver": solver,
        "representation": representation,
        "provenance": {
            "reference": reference,
            "source_files": sources(*source_files),
            "solver_rerun_required_for_this_import": rerun,
            "qualification": "Numeric samples imported from the exact qualified benchmark output; no values were fabricated.",
        },
    }


def parse_cdb_nodes(path: Path) -> dict[int, list[float]]:
    nodes: dict[int, list[float]] = {}
    in_block = False
    expected = 0
    for line in path.read_text(encoding="ascii", errors="replace").splitlines():
        if line.startswith("NBLOCK"):
            in_block = True
            expected = int(line.split(",")[-1])
            continue
        if not in_block or line.startswith("("):
            continue
        if line.strip().startswith("-1"):
            break
        if len(line) >= 27:
            node_id = int(line[:9])
            # NBLOCK's declared ``(3i9,6e21.13e3)`` fixed-width format may
            # omit a trailing zero coordinate as a blank field.
            fields = [line[start : start + 21].strip() for start in (27, 48, 69)]
            nodes[node_id] = [float(value) if value else 0.0 for value in fields]
            if len(nodes) == expected:
                break
    if not nodes:
        raise ValueError(f"no CDB nodes parsed from {rel(path)}")
    return nodes


def parse_result_table(path: Path) -> dict[int, float]:
    result: dict[int, float] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[1:]:
        parts = line.split()
        if len(parts) >= 2:
            try:
                result[int(parts[0])] = float(parts[1])
            except ValueError:
                continue
    if not result:
        raise ValueError(f"no result values parsed from {rel(path)}")
    return result


def import_mechanics() -> dict[str, Any]:
    out = ROOT / "artifacts/runs/mechanics/static-cantilever/20260821T153709Z/outputs"
    result = out / "static_cantilever_results.json"
    cdb = out / "static_cantilever_model.cdb"
    deformation_file = out / "static_cantilever_deformation.txt"
    stress_file = out / "static_cantilever_equivalent_stress.txt"
    payload = require_pass(result)
    nodes = parse_cdb_nodes(cdb)
    deformation = parse_result_table(deformation_file)
    stress = parse_result_table(stress_file)
    common = sorted(nodes.keys() & deformation.keys() & stress.keys())
    if len(common) != payload["mesh"]["node_count"]:
        raise ValueError("mechanics evidence does not cover every solved node")
    evidence = base_evidence(
        "mechanics",
        solver="Mechanical 2026 R1 / MAPDL 261",
        representation="3-D nodal displacement magnitude and equivalent stress",
        reference="artifacts/runs/mechanics/static-cantilever/20260821T153709Z/run.json",
        source_files=(result, cdb, deformation_file, stress_file),
        rerun=True,
    )
    evidence["units"] = {"coordinates": "m", "displacement": "m", "equivalent_stress": "Pa"}
    evidence["validation"] = {
        "maximum_displacement_m": payload["results"]["maximum_total_deformation_m"],
        "maximum_equivalent_stress_pa": payload["results"]["maximum_equivalent_stress_pa"],
        "deflection_relative_error": payload["results"]["relative_error"],
    }
    evidence["data"] = {
        "node_id": common,
        "coordinates": [nodes[node] for node in common],
        "displacement": [deformation[node] for node in common],
        "equivalent_stress": [stress[node] for node in common],
    }
    return evidence


def import_thermal() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs"
    raw = out / "thermal_conduction_raw.csv"
    result = out / "thermal_conduction_results.json"
    payload = require_pass(result)
    by_x: dict[float, list[float]] = {}
    with raw.open(encoding="utf-8-sig", newline="") as stream:
        for row in csv.reader(stream):
            if len(row) >= 3:
                by_x.setdefault(float(row[1]), []).append(float(row[2]))
    curve = [[x, sum(values) / len(values)] for x, values in sorted(by_x.items())]
    evidence = base_evidence(
        "thermal",
        solver="MAPDL 261 / SOLID70",
        representation="solver-nodal temperature field extruded across the solved rectangular section",
        reference="benchmarks/thermal/references/historical_results.json",
        source_files=(raw, result),
        rerun=False,
    )
    evidence["units"] = {"x": "m", "temperature": "degC"}
    evidence["validation"] = payload["errors"]
    evidence["geometry"] = {"length_m": 0.1, "width_m": 0.02, "height_m": 0.02}
    evidence["data"] = {"x_temperature": curve}
    return evidence


def import_cfd() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs"
    field = out / "fluent_cylinder_unsteady_snapshot_t120.0.npz"
    result = out / "fluent_cylinder_unsteady.json"
    payload = require_pass(result)
    with np.load(field, allow_pickle=False) as data:
        coords = data["coordinates"]
        speed = np.hypot(data["velocity_x"], data["velocity_y"])
        pressure = data["pressure"]
        time_s = float(data["time"])
    indices = np.linspace(0, len(coords) - 1, min(2200, len(coords)), dtype=int)
    evidence = base_evidence(
        "cfd",
        solver="Fluent 261 transient laminar",
        representation="2-D solver-node wake velocity and pressure field",
        reference="benchmarks/cfd/references/historical_results.json",
        source_files=(field, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "velocity_magnitude": "m/s", "pressure": "Pa", "time": "s"}
    evidence["validation"] = payload.get("errors", payload.get("results", {}))
    evidence["data"] = {
        "time_s": time_s,
        "coordinates": coords[indices].tolist(),
        "velocity_magnitude": speed[indices].tolist(),
        "pressure": pressure[indices].tolist(),
    }
    return evidence


def import_multiphysics() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs"
    field = out / "cht_fluent_fields.npz"
    result = out / "cht_fluent.json"
    payload = require_pass(result)
    with np.load(field, allow_pickle=False) as data:
        coords = data["coordinates"]
        temperature = data["temperature"]
        speed = np.hypot(data["velocity_x"], data["velocity_y"])
    evidence = base_evidence(
        "multiphysics",
        solver="Fluent 261 conjugate heat transfer",
        representation="conformal fluid-solid solver temperature field",
        reference="benchmarks/multiphysics/references/historical_results.json",
        source_files=(field, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "temperature": "K", "velocity_magnitude": "m/s"}
    evidence["validation"] = payload.get("errors", payload.get("checks", {}))
    evidence["data"] = {
        "coordinates": coords.tolist(),
        "temperature": temperature.tolist(),
        "velocity_magnitude": speed.tolist(),
        "interface_y_m": 0.02,
    }
    return evidence


def import_materials() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/materials/plasticity"
    curve = out / "plasticity_curve.csv"
    result = out / "plasticity_results.json"
    payload = require_pass(result)
    rows = []
    with curve.open(encoding="utf-8-sig", newline="") as stream:
        for row in csv.DictReader(stream):
            rows.append({name: float(value) for name, value in row.items() if name != "step"})
    evidence = base_evidence(
        "materials",
        solver="MAPDL 261 / SOLID185 BISO",
        representation="solver-derived bilinear plasticity load-unload response",
        reference="benchmarks/materials/references/historical_results.json",
        source_files=(curve, result),
        rerun=False,
    )
    evidence["units"] = {"stress": "Pa", "strain": "1"}
    evidence["validation"] = payload["errors"]
    evidence["data"] = {"response": rows}
    return evidence


def import_electromagnetics() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/electromagnetics/case_c_magnetostatic"
    field = out / "field_Mag_B.fld"
    result = out / "result.json"
    payload = require_pass(result)
    samples = []
    for line in field.read_text(encoding="utf-8", errors="replace").splitlines()[2:]:
        parts = line.split()
        if len(parts) >= 4:
            samples.append([float(parts[0]), float(parts[-1])])
    evidence = base_evidence(
        "electromagnetics",
        solver="Maxwell 2D 261 magnetostatic",
        representation="axisymmetric reconstruction of exported radial Mag_B grid samples",
        reference="benchmarks/electromagnetics/references/suite_summary.json",
        source_files=(field, result),
        rerun=False,
    )
    evidence["units"] = {"radius": "m", "magnetic_flux_density": "T"}
    evidence["validation"] = payload["relative_error"]
    evidence["geometry"] = payload["geometry"]
    evidence["data"] = {"radius_B": samples}
    return evidence


def import_acoustics() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/acoustics/case_b_cavity_modal"
    field = out / "mode1_pressure.csv"
    result = out / "case_b_results.json"
    payload = require_pass(result)
    rows = []
    with field.open(encoding="utf-8-sig", newline="") as stream:
        for row in csv.reader(stream):
            if len(row) >= 5:
                rows.append([float(value) for value in row[1:5]])
    evidence = base_evidence(
        "acoustics",
        solver="MAPDL 261 / FLUID30",
        representation="3-D nodal acoustic pressure mode shown on orthogonal slices",
        reference="benchmarks/acoustics/references/suite_summary.json",
        source_files=(field, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "pressure": "Pa (eigenvector scale)"}
    evidence["validation"] = {"mode_1_frequency_hz": payload["results"]["modes"][0]["numerical_hz"], "maximum_frequency_relative_error": payload["errors"]["maximum_relative_error"]}
    evidence["geometry"] = payload["geometry"]
    evidence["data"] = {"xyzt_pressure": rows}
    return evidence


def import_porous() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/porous_geomechanics/terzaghi_consolidation"
    field = out / "terzaghi_field.npz"
    result = out / "terzaghi_consolidation_results.json"
    payload = require_pass(result)
    with np.load(field, allow_pickle=False) as data:
        coords = data["coordinates"]
        times = data["time"]
        pressure = data["pore_pressure"]
        displacement = data["displacement"]
    indices = [0, len(times) // 2, len(times) - 1]
    evidence = base_evidence(
        "porous_geomechanics",
        solver="MAPDL 261 / CPT212",
        representation="transient pore-pressure and settlement field snapshots",
        reference="benchmarks/porous_geomechanics/references/suite_summary.json",
        source_files=(field, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "time": "s", "pore_pressure": "Pa", "displacement": "m"}
    evidence["validation"] = payload["errors"]
    evidence["data"] = {
        "coordinates": coords.tolist(),
        "times_s": times[indices].tolist(),
        "pore_pressure": pressure[indices].tolist(),
        "displacement": displacement[indices].tolist(),
    }
    return evidence


def import_dem() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/rocky_dem/case_d_angle_of_repose"
    table = out / "mu_0p60/particles.csv"
    result = out / "result.json"
    payload = require_pass(result)
    rows = []
    with table.open(encoding="utf-8-sig", newline="") as stream:
        raw = list(csv.DictReader(stream))
    final_time = max(float(row["time_s"]) for row in raw)
    for row in raw:
        if math.isclose(float(row["time_s"]), final_time):
            velocity = math.sqrt(sum(float(row[f"velocity_{axis}_m_per_s"]) ** 2 for axis in "xyz"))
            rows.append([
                float(row["position_x_m"]),
                float(row["position_y_m"]),
                float(row["position_z_m"]),
                velocity,
                float(row["particle_size_m"]),
            ])
    evidence = base_evidence(
        "dem",
        solver="Rocky 261 DEM",
        representation="final 3-D particle configuration colored by speed",
        reference="benchmarks/dem/references/suite_summary.json",
        source_files=(table, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "velocity_magnitude": "m/s", "particle_size": "m", "time": "s"}
    evidence["validation"] = {"angle_of_repose_deg": payload["high_friction"]["angle_of_repose_deg"], "particle_count": payload["high_friction"]["particle_count_final"]}
    evidence["data"] = {"time_s": final_time, "xyz_speed_size": rows}
    return evidence


def import_sph() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/sph_free_surface/case_b_dam_break"
    table = out / "sph_lagrangian.csv"
    result = out / "result.json"
    payload = require_pass(result)
    selected = (0.0, 0.2, 0.45)
    snapshots: dict[str, list[list[float]]] = {f"{time:.2f}": [] for time in selected}
    with table.open(encoding="utf-8-sig", newline="") as stream:
        for row in csv.DictReader(stream):
            time = float(row["time_s"])
            if any(math.isclose(time, target) for target in selected):
                speed = math.sqrt(sum(float(row[f"velocity_{axis}_m_per_s"]) ** 2 for axis in "xyz"))
                snapshots[f"{time:.2f}"].append([float(row["position_x_m"]), float(row["position_z_m"]), speed])
    evidence = base_evidence(
        "sph",
        solver="Rocky 261 SPH",
        representation="solver Lagrangian free-surface particle snapshots",
        reference="benchmarks/sph/references/suite_summary.json",
        source_files=(table, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "velocity_magnitude": "m/s", "time": "s"}
    evidence["validation"] = {"relative_mass_drift": payload["relative_mass_drift"], "element_count": payload["element_count"]}
    evidence["data"] = {"snapshots": snapshots}
    return evidence


def parse_pcm_snapshot(path: Path) -> list[list[float]]:
    rows = []
    with path.open(encoding="utf-8-sig", newline="") as stream:
        reader = csv.reader(stream)
        next(reader)
        for row in reader:
            if len(row) >= 7:
                rows.append([float(row[1]), float(row[2]), float(row[5]), float(row[6])])
    unique = {(round(row[0], 12), round(row[1], 12)): row for row in rows}
    return list(unique.values())


def import_phase() -> dict[str, Any]:
    out = ROOT / "artifacts/legacy/outputs/phase_reactive"
    files = [out / name for name in ("case_b_t00300.csv", "case_b_t00900.csv", "case_b_t03600.csv")]
    result = out / "case_b.json"
    payload = require_pass(result)
    evidence = base_evidence(
        "phase_reactive",
        solver="Fluent 261 enthalpy-porosity",
        representation="transient solver temperature and liquid-fraction fields",
        reference="benchmarks/phase_reactive/references/suite_summary.json",
        source_files=(*files, result),
        rerun=False,
    )
    evidence["units"] = {"coordinates": "m", "temperature": "K", "liquid_fraction": "1", "time": "s"}
    evidence["validation"] = {"sparse_energy_balance_relative_error": payload["results"]["sparse_energy_balance_relative_error"], "final_average_liquid_fraction": payload["results"]["average_liquid_fraction"][-1]}
    evidence["data"] = {"snapshots": {time: parse_pcm_snapshot(path) for time, path in zip(("300", "900", "3600"), files, strict=True)}}
    return evidence


IMPORTERS = {
    "mechanics": import_mechanics,
    "thermal": import_thermal,
    "cfd": import_cfd,
    "multiphysics": import_multiphysics,
    "materials": import_materials,
    "electromagnetics": import_electromagnetics,
    "acoustics": import_acoustics,
    "porous_geomechanics": import_porous,
    "dem": import_dem,
    "sph": import_sph,
    "phase_reactive": import_phase,
}


def evidence_path(domain: str) -> Path:
    return ASSET_ROOT / domain / f"{SLUGS[domain]}.evidence.json"


def visual_path(domain: str) -> Path:
    return ASSET_ROOT / domain / f"{SLUGS[domain]}.svg"


def png_path(domain: str) -> Path:
    return ASSET_ROOT / domain / f"{SLUGS[domain]}.png"


def dump_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False, allow_nan=False, sort_keys=True) + "\n"


def color(value: float, minimum: float, maximum: float) -> str:
    fraction = 0.5 if maximum <= minimum else min(1.0, max(0.0, (value - minimum) / (maximum - minimum)))
    return PALETTE[min(len(PALETTE) - 1, int(fraction * len(PALETTE)))]


def fit(values: Iterable[float], start: float, span: float, *, reverse: bool = False) -> tuple[dict[float, float], float, float]:
    values = list(values)
    low, high = min(values), max(values)
    scale = span / max(high - low, 1e-30)
    mapped = {value: start + (high - value if reverse else value - low) * scale for value in set(values)}
    return mapped, low, high


def circles(points: list[list[float]], values: list[float], *, box: tuple[float, float, float, float], radius: float = 2.5) -> str:
    x0, y0, width, height = box
    xs, ys = [point[0] for point in points], [point[1] for point in points]
    xmap, _, _ = fit(xs, x0, width)
    ymap, _, _ = fit(ys, y0, height, reverse=True)
    vmin, vmax = min(values), max(values)
    return "".join(f'<circle cx="{xmap[x]:.2f}" cy="{ymap[y]:.2f}" r="{radius:.2f}" fill="{color(value, vmin, vmax)}"/>' for (x, y), value in zip(points, values, strict=True))


def line_plot(xs: list[float], ys: list[float], *, box: tuple[float, float, float, float], stroke: str, width: float = 4) -> str:
    x0, y0, w, h = box
    xmap, _, _ = fit(xs, x0, w)
    ymap, _, _ = fit(ys, y0, h, reverse=True)
    points = " ".join(f"{xmap[x]:.2f},{ymap[y]:.2f}" for x, y in zip(xs, ys, strict=True))
    return f'<polyline points="{points}" fill="none" stroke="{stroke}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round"/>'


def legend(label: str, minimum: float, maximum: float) -> str:
    bands = []
    for index, shade in enumerate(reversed(PALETTE)):
        bands.append(f'<rect x="842" y="{142 + index * 29}" width="24" height="30" fill="{shade}"/>')
    return "".join(bands) + f'<text x="878" y="151" class="small">{maximum:.4g}</text><text x="878" y="394" class="small">{minimum:.4g}</text><text x="842" y="428" class="label">{html.escape(label)}</text>'


def frame(title: str, subtitle: str, body: str, *, legend_spec: tuple[str, float, float] | None, footer: str) -> str:
    legend_svg = legend(*legend_spec) if legend_spec else ""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540" role="img" aria-labelledby="title desc">
<!-- {MARKER} -->
<title id="title">{html.escape(title)}</title><desc id="desc">{html.escape(subtitle)}</desc>
<defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#071321"/><stop offset="1" stop-color="#10283e"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="5" stdDeviation="8" flood-opacity=".25"/></filter></defs>
<style>.title{{font:700 26px ui-sans-serif,system-ui;fill:#f5fbff}}.sub{{font:14px ui-sans-serif,system-ui;fill:#a9c2d5}}.label{{font:600 12px ui-sans-serif,system-ui;fill:#dcecf7}}.small{{font:11px ui-monospace,monospace;fill:#b9d1e2}}.grid{{stroke:#28445c;stroke-width:1}}.axis{{stroke:#7a9bb3;stroke-width:1.5}}</style>
<rect width="960" height="540" rx="18" fill="url(#bg)"/><rect x="28" y="92" width="904" height="366" rx="14" fill="#0b1b2a" stroke="#29475e" filter="url(#shadow)"/>
<text x="34" y="43" class="title">{html.escape(title)}</text><text x="34" y="70" class="sub">{html.escape(subtitle)}</text>
<rect x="852" y="27" width="78" height="30" rx="15" fill="#173d30" stroke="#42d392"/><text x="891" y="47" text-anchor="middle" class="label" fill="#7ff2bd">PASS</text>
{body}{legend_svg}<text x="34" y="502" class="small">{html.escape(footer)}</text><text x="926" y="502" text-anchor="end" class="small">solver-derived · deterministic SVG</text>
</svg>\n'''


def render_mechanics(e: dict[str, Any]) -> str:
    coords = e["data"]["coordinates"]
    disp = e["data"]["displacement"]
    stress = e["data"]["equivalent_stress"]
    projected = [[p[0] + 0.55 * p[1], p[2] - 0.35 * p[1]] for p in coords]
    body = circles(projected, disp, box=(78, 150, 700, 190), radius=3.4)
    body += '<line x1="78" y1="130" x2="78" y2="385" stroke="#d6e6ef" stroke-width="5"/><text x="78" y="420" text-anchor="middle" class="label">fixed</text>'
    body += f'<text x="80" y="125" class="label">621 SOLID186 nodes · max stress {max(stress)/1e6:.3f} MPa</text>'
    return frame("3-D cantilever displacement field", "Mechanical solution mapped back to the imported SOLID186 mesh", body, legend_spec=("|u| [m]", min(disp), max(disp)), footer="mechanics/static-cantilever · fresh Mechanical 2026 R1 result")


def render_thermal(e: dict[str, Any]) -> str:
    curve = e["data"]["x_temperature"]
    xs, temp = [row[0] for row in curve], [row[1] for row in curve]
    xmap, _, _ = fit(xs, 100, 650)
    body = ""
    for index, (x, value) in enumerate(zip(xs, temp, strict=True)):
        next_x = xmap[xs[min(index + 1, len(xs) - 1)]] if index + 1 < len(xs) else 770
        width = max(8, next_x - xmap[x] + 1)
        shade = color(value, min(temp), max(temp))
        body += f'<path d="M{xmap[x]:.1f},190 l28,-24 h{width:.1f} l-28,24 z M{xmap[x]:.1f},190 h{width:.1f} v120 h-{width:.1f} z" fill="{shade}" stroke="#14283a" stroke-width=".8"/>'
    body += line_plot(xs, temp, box=(100, 345, 650, 70), stroke="#f7fbff", width=3)
    body += '<text x="100" y="438" class="label">solver nodes: hot wall → cold wall</text>'
    return frame("Steady conduction temperature field", "MAPDL SOLID70 nodal temperature across a 3-D rectangular solid", body, legend_spec=("T [°C]", min(temp), max(temp)), footer="thermal/thermal-conduction · historical qualified solver evidence")


def render_cfd(e: dict[str, Any]) -> str:
    coords = e["data"]["coordinates"]
    speed = e["data"]["velocity_magnitude"]
    body = circles(coords, speed, box=(64, 132, 735, 275), radius=2.0)
    body += '<circle cx="244" cy="270" r="17" fill="#071321" stroke="#eef7fb" stroke-width="2"/><path d="M265 270 C330 220 405 220 485 255 C560 290 640 300 780 270" fill="none" stroke="#d8f3ff" stroke-opacity=".55" stroke-width="1.5" stroke-dasharray="5 6"/>'
    body += f'<text x="66" y="430" class="label">Re=100 · t={e["data"]["time_s"]:.1f} s · transient wake snapshot</text>'
    return frame("Cylinder wake velocity field", "Fluent transient laminar solution; colored solver-node velocity magnitude", body, legend_spec=("|V| [m/s]", min(speed), max(speed)), footer="cfd/fluent-cylinder-unsteady · historical qualified solver evidence")


def render_multiphysics(e: dict[str, Any]) -> str:
    coords = e["data"]["coordinates"]
    temp = e["data"]["temperature"]
    body = circles(coords, temp, box=(76, 132, 710, 275), radius=3.0)
    ys = [point[1] for point in coords]
    ymap, _, _ = fit(ys, 132, 275, reverse=True)
    interface = ymap[e["data"]["interface_y_m"]]
    body += f'<line x1="76" y1="{interface:.1f}" x2="786" y2="{interface:.1f}" stroke="#f7fbff" stroke-width="2" stroke-dasharray="8 6"/><text x="88" y="{interface-8:.1f}" class="label">fluid / solid interface</text>'
    return frame("Conjugate heat-transfer field", "Fluent temperature spanning conformal fluid and solid logical domains", body, legend_spec=("T [K]", min(temp), max(temp)), footer="multiphysics/cht-fluent · historical qualified solver evidence")


def render_materials(e: dict[str, Any]) -> str:
    rows = e["data"]["response"]
    strain = [row["total_strain"] for row in rows]
    theory = [row["theory_total_strain"] for row in rows]
    stress = [row["stress_pa"] / 1e6 for row in rows]
    body = '<line x1="105" y1="405" x2="785" y2="405" class="axis"/><line x1="105" y1="120" x2="105" y2="405" class="axis"/>'
    body += line_plot(strain, stress, box=(105, 120, 680, 285), stroke="#48d7c8", width=5)
    body += line_plot(theory, stress, box=(105, 120, 680, 285), stroke="#f6c85f", width=2)
    body += '<text x="115" y="142" class="label">MAPDL response</text><text x="245" y="142" class="label" fill="#f6c85f">bilinear theory</text><text x="690" y="435" class="label">strain [-]</text><text x="48" y="118" class="label">stress [MPa]</text>'
    return frame("Bilinear plasticity load–unload", "SOLID185 BISO response with yielding, unloading, and residual strain", body, legend_spec=None, footer="materials/plasticity · historical qualified solver evidence")


def render_electromagnetics(e: dict[str, Any]) -> str:
    samples = e["data"]["radius_B"]
    radii, values = [row[0] for row in samples], [row[1] for row in samples]
    body = '<circle cx="420" cy="276" r="202" fill="#071321" stroke="#59778e" stroke-width="2"/>'
    for radius, value in reversed(samples):
        rr = 58 + (radius - min(radii)) / (max(radii) - min(radii)) * 135
        body += f'<circle cx="420" cy="276" r="{rr:.2f}" fill="{color(value, min(values), max(values))}" stroke="#0b1b2a" stroke-width="2"/>'
    body += '<circle cx="420" cy="276" r="54" fill="#c08a4b" stroke="#f6d5a5" stroke-width="2"/><circle cx="420" cy="276" r="196" fill="none" stroke="#c08a4b" stroke-width="16"/><text x="420" y="281" text-anchor="middle" class="label">+100 A</text><text x="420" y="85" text-anchor="middle" class="label">−100 A return</text>'
    return frame("Coaxial magnetic flux-density field", "Maxwell 2-D radial Mag_B samples revolved by the solved axisymmetry", body, legend_spec=("|B| [T]", min(values), max(values)), footer="electromagnetics/magnetostatic · historical qualified solver evidence")


def render_acoustics(e: dict[str, Any]) -> str:
    rows = e["data"]["xyzt_pressure"]
    pressure = [row[3] for row in rows]
    coordinates = [row[:3] for row in rows]
    mids = []
    for axis in range(3):
        levels = sorted({point[axis] for point in coordinates})
        mids.append(levels[len(levels) // 2])
    body = ""
    labels = ("x-mid: y–z", "y-mid: x–z", "z-mid: x–y")
    axes = ((1, 2), (0, 2), (0, 1))
    for panel, (fixed, pair) in enumerate(zip(range(3), ((0, axes[0]), (1, axes[1]), (2, axes[2])), strict=True)):
        fixed_axis, (a, b) = pair
        chosen = [(point, value) for point, value in zip(coordinates, pressure, strict=True) if math.isclose(point[fixed_axis], mids[fixed_axis], abs_tol=1e-12)]
        points = [[point[a], point[b]] for point, _ in chosen]
        values = [value for _, value in chosen]
        x0 = 55 + panel * 255
        body += f'<rect x="{x0}" y="138" width="220" height="235" fill="#071321" stroke="#35556d"/><text x="{x0+110}" y="405" text-anchor="middle" class="label">{labels[panel]}</text>'
        body += circles(points, values, box=(x0 + 8, 146, 204, 219), radius=5.3)
    return frame("3-D acoustic cavity mode", "MAPDL FLUID30 eigenvector pressure on three orthogonal mid-planes", body, legend_spec=("p [Pa*]", min(pressure), max(pressure)), footer="acoustics/acoustic-cavity-modal · mode 1 at 286.851 Hz")


def render_porous(e: dict[str, Any]) -> str:
    coords = e["data"]["coordinates"]
    snapshots = e["data"]["pore_pressure"]
    times = e["data"]["times_s"]
    all_values = [value for row in snapshots for value in row]
    body = ""
    for panel, (time, values) in enumerate(zip(times, snapshots, strict=True)):
        x0 = 95 + panel * 225
        body += f'<rect x="{x0}" y="132" width="145" height="275" rx="4" fill="#071321" stroke="#35556d"/>'
        body += circles(coords, values, box=(x0 + 12, 142, 121, 255), radius=8.2)
        settlement = max(abs(item[1]) for item in e["data"]["displacement"][panel])
        body += f'<text x="{x0+72}" y="430" text-anchor="middle" class="label">t={time:.3g} s</text><text x="{x0+72}" y="449" text-anchor="middle" class="small">|u|={settlement:.3g} m</text>'
    return frame("Terzaghi consolidation field", "MAPDL CPT212 pore-pressure dissipation with settlement snapshots", body, legend_spec=("p [Pa]", min(all_values), max(all_values)), footer="porous_geomechanics/terzaghi-consolidation · historical qualified solver evidence")


def render_dem(e: dict[str, Any]) -> str:
    rows = e["data"]["xyz_speed_size"]
    projected = [[row[0] + 0.5 * row[1], row[2] - 0.22 * row[1]] for row in rows]
    speed = [row[3] for row in rows]
    body = '<path d="M95 385 L710 385 L760 350 L145 350 Z" fill="#263c4d" stroke="#7695aa"/>'
    body += circles(projected, speed, box=(120, 160, 620, 225), radius=7.5)
    body += f'<text x="110" y="430" class="label">69 Rocky particles · repose angle {e["validation"]["angle_of_repose_deg"]:.2f}°</text>'
    return frame("DEM angle-of-repose particles", "Rocky final 3-D particle configuration for the high-friction material", body, legend_spec=("|V| [m/s]", min(speed), max(speed)), footer="dem/angle-of-repose · historical qualified solver evidence")


def render_sph(e: dict[str, Any]) -> str:
    snapshots = e["data"]["snapshots"]
    all_speed = [row[2] for rows in snapshots.values() for row in rows]
    body = ""
    for panel, (time, rows) in enumerate(sorted(snapshots.items(), key=lambda item: float(item[0]))):
        x0 = 42 + panel * 260
        points = [[row[0], row[1]] for row in rows]
        speed = [row[2] for row in rows]
        body += f'<path d="M{x0} 145 V390 H{x0+230}" fill="none" stroke="#7695aa" stroke-width="3"/><text x="{x0+115}" y="425" text-anchor="middle" class="label">t={float(time):.2f} s</text>'
        body += circles(points, speed, box=(x0 + 8, 154, 214, 225), radius=5.3)
    return frame("SPH dam-break free surface", "Rocky Lagrangian particles colored by velocity at three solver times", body, legend_spec=("|V| [m/s]", min(all_speed), max(all_speed)), footer="sph/sph-dam-break · 0.0% mass drift in qualified run")


def render_phase(e: dict[str, Any]) -> str:
    snapshots = e["data"]["snapshots"]
    all_fraction = [row[3] for rows in snapshots.values() for row in rows]
    body = ""
    for panel, (time, rows) in enumerate(snapshots.items()):
        x0 = 45 + panel * 260
        points = [[row[0], row[1]] for row in rows]
        fraction = [row[3] for row in rows]
        body += f'<rect x="{x0}" y="175" width="230" height="150" fill="#071321" stroke="#35556d"/><text x="{x0+115}" y="360" text-anchor="middle" class="label">t={time} s</text>'
        body += circles(points, fraction, box=(x0 + 6, 182, 218, 136), radius=3.5)
    return frame("PCM melting phase field", "Fluent enthalpy-porosity liquid-fraction evolution in a heated slab", body, legend_spec=("liquid fraction [-]", min(all_fraction), max(all_fraction)), footer="phase_reactive/fluent-melting · historical qualified solver evidence")


RENDERERS = {
    "mechanics": render_mechanics,
    "thermal": render_thermal,
    "cfd": render_cfd,
    "multiphysics": render_multiphysics,
    "materials": render_materials,
    "electromagnetics": render_electromagnetics,
    "acoustics": render_acoustics,
    "porous_geomechanics": render_porous,
    "dem": render_dem,
    "sph": render_sph,
    "phase_reactive": render_phase,
}


def _load_plotting() -> tuple[Any, Any, Any]:
    """Load the optional documentation-visual stack only when PNGs are handled."""
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.tri as mtri
        from PIL import Image
    except ImportError as exc:
        raise RuntimeError("paper-style PNG generation requires the 'visuals' extra") from exc
    plt.rcParams.update({"axes.titlesize": 10, "axes.labelsize": 9, "font.size": 9})
    return plt, mtri, Image


def _figure(plt: Any, evidence: dict[str, Any], title: str, *, width_ratios: list[float] | None = None) -> tuple[Any, Any]:
    columns = 1 if width_ratios is None else len(width_ratios)
    figure, axes = plt.subplots(
        1,
        columns,
        figsize=(PNG_SIZE[0] / PNG_DPI, PNG_SIZE[1] / PNG_DPI),
        constrained_layout=True,
        gridspec_kw={"width_ratios": width_ratios} if width_ratios else None,
        squeeze=False,
    )
    figure.get_layout_engine().set(rect=(0.05, 0.08, 0.98, 0.82))
    figure.suptitle(title, fontsize=15, fontweight="bold", y=0.98)
    figure.text(0.5, 0.915, evidence["solver"], ha="center", va="top", fontsize=8.5, color="#475569")
    figure.text(
        0.02,
        0.018,
        f"Solver-derived compact evidence · {evidence['domain']}/{evidence['case']} · status {evidence['status']}",
        ha="left",
        va="bottom",
        fontsize=7.5,
        color="#64748b",
        zorder=10,
    )
    return figure, axes[0]


def _style_axis(axis: Any, *, equal: bool = False) -> None:
    axis.tick_params(labelsize=8, direction="out")
    axis.grid(False)
    for spine in axis.spines.values():
        spine.set_linewidth(0.7)
        spine.set_color("#64748b")
    if equal:
        axis.set_aspect("equal", adjustable="box")


def _colorbar(figure: Any, artist: Any, axis: Any, label: str) -> None:
    bar = figure.colorbar(artist, ax=axis, pad=0.025, fraction=0.052)
    bar.set_label(label, fontsize=9)
    bar.ax.tick_params(labelsize=8)


def _tri_field(axis: Any, mtri: Any, coordinates: Any, values: Any, *, cmap: str, levels: int = 20) -> Any:
    points = np.asarray(coordinates, dtype=float)
    field = np.asarray(values, dtype=float)
    triangulation = mtri.Triangulation(points[:, 0], points[:, 1])
    return axis.tricontourf(triangulation, field, levels=levels, cmap=cmap, extend="both")


def _grid_field(axis: Any, coordinates: Any, values: Any, *, cmap: str, levels: int = 20) -> Any:
    points = np.asarray(coordinates, dtype=float)
    field = np.asarray(values, dtype=float)
    xs = np.unique(points[:, 0])
    ys = np.unique(points[:, 1])
    if len(xs) * len(ys) != len(points):
        _, mtri, _ = _load_plotting()
        return _tri_field(axis, mtri, points, field, cmap=cmap, levels=levels)
    lookup = {(x, y): value for (x, y), value in zip(points, field, strict=True)}
    grid = np.asarray([[lookup[(x, y)] for x in xs] for y in ys])
    return axis.contourf(xs, ys, grid, levels=levels, cmap=cmap, extend="both")


def _render_mechanics_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure = plt.figure(figsize=(PNG_SIZE[0] / PNG_DPI, PNG_SIZE[1] / PNG_DPI))
    figure.suptitle("Static cantilever: solved nodal fields", fontsize=15, fontweight="bold", y=0.98)
    figure.text(0.5, 0.915, evidence["solver"], ha="center", va="top", fontsize=8.5, color="#475569")
    coordinates = np.asarray(evidence["data"]["coordinates"], dtype=float)
    fields = (
        (np.asarray(evidence["data"]["displacement"]) * 1e3, "Total displacement", "|u| [mm]"),
        (np.asarray(evidence["data"]["equivalent_stress"]) / 1e6, "Equivalent stress", "σᵥₘ [MPa]"),
    )
    positions = ((0.035, 0.19, 0.40, 0.62), (0.535, 0.19, 0.40, 0.62))
    colorbar_positions = ((0.10, 0.11, 0.27, 0.025), (0.60, 0.11, 0.27, 0.025))
    for (values, title, label), position, bar_position in zip(fields, positions, colorbar_positions, strict=True):
        axis = figure.add_axes(position, projection="3d")
        artist = axis.scatter(
            coordinates[:, 0] * 1e3,
            coordinates[:, 1] * 1e3,
            coordinates[:, 2] * 1e3,
            c=values,
            cmap="turbo",
            s=8,
            linewidths=0,
            depthshade=False,
        )
        axis.set_title(title, fontsize=10)
        axis.set_xlabel("x [mm]", fontsize=8)
        axis.set_ylabel("y [mm]", fontsize=8)
        axis.set_zlabel("z [mm]", fontsize=8)
        axis.tick_params(labelsize=7, pad=0)
        axis.view_init(elev=23, azim=-63)
        axis.set_box_aspect((4.6, 1.0, 1.0))
        axis.grid(False)
        bar_axis = figure.add_axes(bar_position)
        bar = figure.colorbar(artist, cax=bar_axis, orientation="horizontal")
        bar.set_label(label, fontsize=8)
        bar.ax.tick_params(labelsize=7)
    figure.text(
        0.02,
        0.018,
        "621 solved SOLID186 nodes · fresh qualified run · displacement magnitude (undeformed coordinates)",
        fontsize=7.5,
        color="#64748b",
        zorder=10,
    )
    return figure


def _render_thermal_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Steady conduction: temperature field and axial profile", width_ratios=[1.35, 1.0])
    curve = np.asarray(evidence["data"]["x_temperature"], dtype=float)
    x_mm = curve[:, 0] * 1e3
    temperature = curve[:, 1]
    field = np.tile(temperature, (61, 1))
    y_mm = np.linspace(-10, 10, field.shape[0])
    artist = axes[0].contourf(x_mm, y_mm, field, levels=np.linspace(20, 120, 21), cmap="inferno")
    axes[0].contour(x_mm, y_mm, field, levels=np.arange(30, 120, 20), colors="white", linewidths=0.5, alpha=0.7)
    axes[0].set(xlabel="x [mm]", ylabel="y [mm]", title="SOLID70 nodal field (transverse extrusion)")
    _style_axis(axes[0])
    _colorbar(figure, artist, axes[0], "Temperature [°C]")
    reference = np.linspace(temperature[0], temperature[-1], len(temperature))
    axes[1].plot(x_mm, reference, color="#334155", linewidth=1.2, linestyle="--", label="linear reference")
    axes[1].plot(x_mm, temperature, "o-", color="#b91c1c", markersize=4, linewidth=1.6, label="solver nodes")
    axes[1].set(xlabel="x [mm]", ylabel="Temperature [°C]", title="Centerline validation")
    axes[1].legend(frameon=False, fontsize=8)
    _style_axis(axes[1])
    return figure


def _render_cfd_png(plt: Any, mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Unsteady cylinder wake at t = 120 s", width_ratios=[1, 1])
    coordinates = np.asarray(evidence["data"]["coordinates"], dtype=float)
    triangulation = mtri.Triangulation(coordinates[:, 0], coordinates[:, 1])
    centers = coordinates[triangulation.triangles].mean(axis=1)
    triangulation.set_mask(np.hypot(centers[:, 0], centers[:, 1]) < 0.52)
    specifications = (
        (evidence["data"]["velocity_magnitude"], "turbo", "Velocity magnitude", "|V| [m/s]"),
        (evidence["data"]["pressure"], "coolwarm", "Static pressure", "p [Pa]"),
    )
    for axis, (values, cmap, title, label) in zip(axes, specifications, strict=True):
        artist = axis.tricontourf(triangulation, values, levels=24, cmap=cmap, extend="both")
        axis.add_patch(plt.Circle((0, 0), 0.5, facecolor="white", edgecolor="#111827", linewidth=1.0, zorder=5))
        axis.set(xlim=(-2.5, 10), ylim=(-3, 3), xlabel="x/D [-]", ylabel="y/D [-]", title=title)
        axis.set_xticks([-2, 4, 10])
        _style_axis(axis, equal=True)
        _colorbar(figure, artist, axis, label)
    return figure


def _render_multiphysics_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Conjugate heat transfer across the fluid–solid interface", width_ratios=[1, 1])
    coordinates = np.asarray(evidence["data"]["coordinates"], dtype=float)
    specifications = (
        (evidence["data"]["temperature"], "inferno", "Temperature field", "T [K]"),
        (evidence["data"]["velocity_magnitude"], "viridis", "Fluid velocity / solid zero field", "|V| [m/s]"),
    )
    for axis, (values, cmap, title, label) in zip(axes, specifications, strict=True):
        artist = _grid_field(axis, coordinates, values, cmap=cmap, levels=24)
        axis.axhline(evidence["data"]["interface_y_m"], color="white", linewidth=1.0, linestyle="--")
        axis.text(0.004, evidence["data"]["interface_y_m"] + 0.0005, "fluid–solid interface", color="white", fontsize=7)
        axis.set(xlabel="x [m]", ylabel="y [m]", title=title)
        _style_axis(axis)
        _colorbar(figure, artist, axis, label)
    return figure


def _render_materials_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Bilinear plasticity: solver load–unload response")
    axis = axes[0]
    rows = evidence["data"]["response"]
    strain = np.asarray([row["total_strain"] for row in rows]) * 1e3
    theory = np.asarray([row["theory_total_strain"] for row in rows]) * 1e3
    stress = np.asarray([row["stress_pa"] for row in rows]) / 1e6
    axis.plot(theory, stress, color="#334155", linewidth=1.3, linestyle="--", label="bilinear reference")
    axis.plot(strain, stress, "o-", color="#0f766e", linewidth=1.8, markersize=4.5, label="SOLID185 response")
    axis.axvline(strain[-1], color="#b91c1c", linewidth=0.9, linestyle=":", label="residual strain")
    axis.set(xlabel="Total strain [10⁻³]", ylabel="Stress [MPa]")
    axis.legend(frameon=False, fontsize=8, loc="lower right")
    axis.grid(True, linewidth=0.4, color="#cbd5e1")
    _style_axis(axis)
    return figure


def _render_electromagnetics_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Coaxial magnetostatic flux-density field")
    axis = axes[0]
    samples = np.asarray(evidence["data"]["radius_B"], dtype=float)
    extent = evidence["geometry"]["return_outer_radius_mm"]
    grid_mm = np.linspace(-extent, extent, 501)
    xx, yy = np.meshgrid(grid_mm, grid_mm)
    radius_m = np.hypot(xx, yy) * 1e-3
    field = np.interp(radius_m, samples[:, 0], samples[:, 1], left=np.nan, right=np.nan)
    artist = axis.contourf(xx, yy, field, levels=24, cmap="magma", extend="both")
    for radius, linestyle in ((5.0, "-"), (19.0, "--"), (20.0, "-")):
        axis.add_patch(plt.Circle((0, 0), radius, fill=False, color="white", linewidth=0.8, linestyle=linestyle))
    axis.set(xlabel="x [mm]", ylabel="y [mm]")
    _style_axis(axis, equal=True)
    _colorbar(figure, artist, axis, "Magnetic flux density |B| [T]")
    return figure


def _render_acoustics_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Rectangular acoustic cavity: first pressure mode", width_ratios=[1, 1, 1])
    rows = np.asarray(evidence["data"]["xyzt_pressure"], dtype=float)
    coordinates, pressure = rows[:, :3], rows[:, 3]
    maximum = float(np.max(np.abs(pressure)))
    pressure[np.abs(pressure) < maximum * 1e-10] = 0.0
    labels = ((0, 1, 2, "x-mid: y–z"), (1, 0, 2, "y-mid: x–z"), (2, 0, 1, "z-mid: x–y"))
    artist = None
    for axis, (fixed, horizontal, vertical, title) in zip(axes, labels, strict=True):
        levels = np.unique(coordinates[:, fixed])
        middle = levels[len(levels) // 2]
        selected = np.isclose(coordinates[:, fixed], middle)
        artist = _grid_field(
            axis,
            coordinates[selected][:, [horizontal, vertical]],
            pressure[selected],
            cmap="coolwarm",
            levels=21,
        )
        artist.set_clim(-maximum, maximum)
        axis.set(xlabel=f"{'xyz'[horizontal]} [m]", ylabel=f"{'xyz'[vertical]} [m]", title=title)
        _style_axis(axis, equal=True)
    assert artist is not None
    _colorbar(figure, artist, list(axes), "Acoustic pressure [Pa, eigenvector scale]")
    figure.text(0.98, 0.018, f"mode 1: {evidence['validation']['mode_1_frequency_hz']:.3f} Hz", ha="right", fontsize=7.5)
    return figure


def _render_porous_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "Terzaghi consolidation: pore-pressure dissipation", width_ratios=[1, 1, 1])
    coordinates = np.asarray(evidence["data"]["coordinates"], dtype=float)
    all_pressure = np.asarray(evidence["data"]["pore_pressure"], dtype=float)
    maximum = float(np.max(all_pressure))
    artist = None
    for axis, time_s, pressure, displacement in zip(
        axes,
        evidence["data"]["times_s"],
        all_pressure,
        evidence["data"]["displacement"],
        strict=True,
    ):
        artist = _grid_field(axis, coordinates, pressure, cmap="Blues", levels=np.linspace(0, maximum, 21))
        settlement = max(abs(row[1]) for row in displacement) * 1e3
        axis.set(
            xlabel="x [m]",
            ylabel="depth z [m]",
            title=f"t = {time_s:.4g} s\n|u|max = {settlement:.3f} mm",
        )
        _style_axis(axis)
    assert artist is not None
    _colorbar(figure, artist, list(axes), "Pore pressure [Pa]")
    return figure


def _render_dem_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure = plt.figure(figsize=(PNG_SIZE[0] / PNG_DPI, PNG_SIZE[1] / PNG_DPI))
    figure.suptitle("DEM angle of repose: final particle configuration", fontsize=15, fontweight="bold", y=0.98)
    figure.text(0.5, 0.915, evidence["solver"], ha="center", va="top", fontsize=8.5, color="#475569")
    axis = figure.add_axes((0.10, 0.14, 0.72, 0.69), projection="3d")
    rows = np.asarray(evidence["data"]["xyz_speed_size"], dtype=float)
    artist = axis.scatter(
        rows[:, 0] * 1e3,
        rows[:, 1] * 1e3,
        rows[:, 2] * 1e3,
        c=rows[:, 3] * 1e3,
        cmap="viridis",
        s=(rows[:, 4] * 1e3 * 5.0) ** 2,
        edgecolors="#334155",
        linewidths=0.25,
        depthshade=True,
    )
    axis.set(xlabel="x [mm]", ylabel="y [mm]", zlabel="z [mm]")
    axis.view_init(elev=22, azim=-55)
    axis.set_box_aspect((1, 1, 0.45))
    axis.tick_params(labelsize=8)
    bar_axis = figure.add_axes((0.86, 0.20, 0.025, 0.56))
    bar = figure.colorbar(artist, cax=bar_axis)
    bar.set_label("Particle speed [mm/s]", fontsize=9)
    bar.ax.tick_params(labelsize=8)
    figure.text(
        0.02,
        0.018,
        f"{len(rows)} solved particles · t = {evidence['data']['time_s']:.2f} s · repose angle {evidence['validation']['angle_of_repose_deg']:.2f}°",
        fontsize=7.5,
        color="#64748b",
        zorder=10,
    )
    return figure


def _render_sph_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "SPH dam break: Lagrangian free-surface evolution", width_ratios=[1, 1, 1])
    snapshots = sorted(evidence["data"]["snapshots"].items(), key=lambda item: float(item[0]))
    maximum = max(row[2] for _, rows in snapshots for row in rows)
    artist = None
    for axis, (time, rows) in zip(axes, snapshots, strict=True):
        samples = np.asarray(rows, dtype=float)
        artist = axis.scatter(samples[:, 0], samples[:, 1], c=samples[:, 2], cmap="turbo", vmin=0, vmax=maximum, s=13, linewidths=0)
        axis.set(xlabel="x [m]", ylabel="z [m]", title=f"t = {float(time):.2f} s")
        axis.set_xlim(-0.15, 0.15)
        axis.set_ylim(0, 0.085)
        _style_axis(axis)
    assert artist is not None
    _colorbar(figure, artist, list(axes), "Particle speed [m/s]")
    return figure


def _render_phase_png(plt: Any, _mtri: Any, evidence: dict[str, Any]) -> Any:
    figure, axes = _figure(plt, evidence, "PCM melting: liquid-fraction evolution", width_ratios=[1, 1, 1])
    snapshots = sorted(evidence["data"]["snapshots"].items(), key=lambda item: float(item[0]))
    artist = None
    for axis, (time, rows) in zip(axes, snapshots, strict=True):
        samples = np.asarray(rows, dtype=float)
        artist = _grid_field(axis, samples[:, :2], samples[:, 3], cmap="plasma", levels=np.linspace(0, 1, 21))
        axis.contour(
            np.unique(samples[:, 0]),
            np.unique(samples[:, 1]),
            samples[:, 3].reshape(len(np.unique(samples[:, 1])), len(np.unique(samples[:, 0]))),
            levels=[0.5],
            colors="white",
            linewidths=1.0,
        )
        axis.set(xlabel="x [m]", ylabel="y [m]", title=f"t = {float(time):.0f} s")
        _style_axis(axis)
    assert artist is not None
    _colorbar(figure, artist, list(axes), "Liquid fraction [-]")
    return figure


PNG_RENDERERS = {
    "mechanics": _render_mechanics_png,
    "thermal": _render_thermal_png,
    "cfd": _render_cfd_png,
    "multiphysics": _render_multiphysics_png,
    "materials": _render_materials_png,
    "electromagnetics": _render_electromagnetics_png,
    "acoustics": _render_acoustics_png,
    "porous_geomechanics": _render_porous_png,
    "dem": _render_dem_png,
    "sph": _render_sph_png,
    "phase_reactive": _render_phase_png,
}


def _png_description(domain: str) -> str:
    return f"evidence_sha256={sha256(evidence_path(domain))};render_version={PNG_RENDER_VERSION};domain={domain}"


def render_or_check_pngs(evidence: dict[str, dict[str, Any]], *, check: bool) -> int:
    plt, mtri, Image = _load_plotting()
    stale = []
    for domain in DOMAINS:
        path = png_path(domain)
        description = _png_description(domain)
        if check:
            try:
                with Image.open(path) as image:
                    if image.size != PNG_SIZE or image.info.get("Description") != description:
                        stale.append(rel(path))
            except (FileNotFoundError, OSError):
                stale.append(rel(path))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        figure = PNG_RENDERERS[domain](plt, mtri, evidence[domain])
        figure.savefig(
            path,
            dpi=PNG_DPI,
            facecolor="white",
            metadata={"Software": "agentic-ansys-lab", "Description": description},
        )
        plt.close(figure)
    if stale:
        print("stale paper-style PNGs: " + ", ".join(stale))
        return 1
    return 0


def render_montage(evidence: dict[str, dict[str, Any]]) -> str:
    picks = ("mechanics", "cfd", "multiphysics", "electromagnetics", "acoustics", "dem", "sph", "phase_reactive")
    tiles = []
    for index, domain in enumerate(picks):
        x = 24 + (index % 4) * 234
        y = 86 + (index // 4) * 207
        payload = evidence[domain]
        data = payload["data"]
        if domain == "mechanics":
            points = [[p[0] + 0.55 * p[1], p[2] - 0.35 * p[1]] for p in data["coordinates"]]
            values = data["displacement"]
        elif domain in {"cfd", "multiphysics"}:
            points = data["coordinates"]
            values = data["velocity_magnitude"] if domain == "cfd" else data["temperature"]
        elif domain == "electromagnetics":
            points, values = [], []
            for radius, field_value in data["radius_B"]:
                for angle in range(0, 360, 12):
                    radians = math.radians(angle)
                    points.append([radius * math.cos(radians), radius * math.sin(radians)])
                    values.append(field_value)
        elif domain == "acoustics":
            rows = data["xyzt_pressure"]
            levels = sorted({row[2] for row in rows})
            middle = levels[len(levels) // 2]
            selected = [row for row in rows if math.isclose(row[2], middle, abs_tol=1e-12)]
            points = [row[:2] for row in selected]
            values = [row[3] for row in selected]
        elif domain == "dem":
            points = [[row[0] + 0.5 * row[1], row[2] - 0.22 * row[1]] for row in data["xyz_speed_size"]]
            values = [row[3] for row in data["xyz_speed_size"]]
        elif domain == "sph":
            rows = data["snapshots"]["0.45"]
            points = [row[:2] for row in rows]
            values = [row[2] for row in rows]
        else:
            rows = data["snapshots"]["3600"]
            points = [row[:2] for row in rows]
            values = [row[3] for row in rows]
        stride = max(1, len(points) // 420)
        points, values = points[::stride], values[::stride]
        sample_svg = circles(points, values, box=(x + 12, y + 60, 192, 91), radius=1.9 if len(points) > 100 else 3.8)
        tiles.append(f'<a href="{domain}/{SLUGS[domain]}.svg"><rect x="{x}" y="{y}" width="216" height="178" rx="12" fill="#0b1b2a" stroke="#35556d"/><text x="{x+14}" y="{y+27}" class="label">{html.escape(domain.replace("_", " ").title())}</text><text x="{x+14}" y="{y+48}" class="small">{html.escape(payload["case"])}</text>{sample_svg}<text x="{x+14}" y="{y+167}" class="small">solver-derived samples → full visual</text></a>')
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="960" height="520" viewBox="0 0 960 520" role="img" aria-labelledby="title desc">
<!-- {MARKER} --><title id="title">Real solver-derived simulation showcase</title><desc id="desc">Eight representative result visuals across the simulation laboratory.</desc>
<style>.title{{font:700 27px ui-sans-serif,system-ui;fill:#f5fbff}}.sub{{font:14px ui-sans-serif,system-ui;fill:#a9c2d5}}.label{{font:700 14px ui-sans-serif,system-ui;fill:#e9f5fb}}.small{{font:11px ui-monospace,monospace;fill:#9fc0d4}}a{{text-decoration:none}}</style><rect width="960" height="520" rx="18" fill="#071321"/><text x="24" y="38" class="title">Real solver-derived simulation showcase</text><text x="24" y="64" class="sub">Eight physics domains · PASS evidence · deterministic project-owned post-processing</text>{''.join(tiles)}<text x="24" y="495" class="small">Open a tile for the full field visual, legend, benchmark provenance, and validation context.</text></svg>\n'''


def expected_outputs() -> dict[Path, str]:
    evidence = {domain: read_json(evidence_path(domain)) for domain in DOMAINS}
    outputs = {visual_path(domain): RENDERERS[domain](evidence[domain]) for domain in DOMAINS}
    outputs[ASSET_ROOT / "montage.svg"] = render_montage(evidence)
    return outputs


def write_or_check(outputs: dict[Path, str], *, check: bool) -> int:
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(rel(path))
        else:
            if path.is_file() and path.read_text(encoding="utf-8") == content:
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("stale simulation visuals: " + ", ".join(stale))
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--import-local", action="store_true", help="import qualified ignored solver outputs into sanitized JSON")
    parser.add_argument("--check", action="store_true", help="fail if rendered SVG/PNG assets are stale")
    args = parser.parse_args(argv)
    if args.import_local and args.check:
        parser.error("--import-local and --check are mutually exclusive")
    if args.import_local:
        for domain in DOMAINS:
            path = evidence_path(domain)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(dump_json(IMPORTERS[domain]()), encoding="utf-8", newline="\n")
            print(f"imported {rel(path)}")
    missing = [rel(evidence_path(domain)) for domain in DOMAINS if not evidence_path(domain).is_file()]
    if missing:
        print("missing sanitized evidence: " + ", ".join(missing))
        return 2
    evidence = {domain: read_json(evidence_path(domain)) for domain in DOMAINS}
    status = write_or_check(expected_outputs(), check=args.check)
    status |= render_or_check_pngs(evidence, check=args.check)
    if not status:
        print("simulation visuals: PASS" if args.check else "simulation visuals: built")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
